
spring.application.name: PlayerServer

server.port: 49561

logging:
  level:
    de.dirdra: DEBUG
    org.springframework.web.client: DEBUG

# Eurekaeinstellungen
#eureka:
#	client.service-url:
#		defaultZone: http://localhost:8301/eureka



# Datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/playerService
    platform: h2
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update