
spring.application.name: PlayerServer

server.port: 49561

logging:
  level:
    de.dirdra: DEBUG
    org.springframework.web.client: DEBUG

# Eurekaeinstellungen
#eureka:
#	client.service-url:
#		defaultZone: http://localhost:8301/eureka

