spring.application.name: CensusEventServer

server.port: 0

logging.level.de.dirdra: debug
logging.level.feign: debug



playerservice.url.getCharByID: http://PlayerServer/import/character/{id}